# Generated by Django 6.1.1 on 2026-09-22 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escopo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('texto_extraido', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'pendente'), ('processado', 'processado'), ('erro', 'erro')], default='pendente', max_length=20)),
                ('data_upload', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'escopos',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'projetos',
            },
        ),
        migrations.CreateModel(
            name='CasoDeTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('funcional', 'funcional'), ('integracao', 'integracao'), ('regra_de_negocio', 'regra_de_negocio'), ('outro', 'outro')], default='funcional', max_length=20)),
                ('pre_condicao', models.TextField(blank=True, null=True)),
                ('passos', models.TextField(blank=True, null=True)),
                ('resultado_esperado', models.TextField(blank=True, null=True)),
                ('prioridade', models.CharField(choices=[('baixa', 'baixa'), ('media', 'media'), ('alta', 'alta')], default='media', max_length=20)),
                ('origem', models.CharField(choices=[('manual', 'manual'), ('ia', 'ia')], default='manual', max_length=20)),
                ('escopo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_de_teste', to='modelos.escopo')),
            ],
            options={
                'db_table': 'casos_de_teste',
            },
        ),
        migrations.CreateModel(
            name='ExecucaoDeCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'pendente'), ('passou', 'passou'), ('falhou', 'falhou'), ('bloqueado', 'bloqueado')], default='pendente', max_length=20)),
                ('observacoes', models.CharField(blank=True, max_length=1000, null=True)),
                ('data_execucao', models.DateTimeField(blank=True, null=True)),
                ('caso_de_teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='modelos.casodeteste')),
            ],
            options={
                'db_table': 'execucoes_caso',
            },
        ),
        migrations.CreateModel(
            name='Defeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
                ('severidade', models.CharField(choices=[('baixa', 'baixa'), ('media', 'media'), ('alta', 'alta'), ('critica', 'critica')], default='media', max_length=20)),
                ('status', models.CharField(choices=[('aberto', 'aberto'), ('em_analise', 'em_analise'), ('corrigido', 'corrigido'), ('fechado', 'fechado')], default='aberto', max_length=20)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defeitos', to='modelos.execucaodecaso')),
            ],
            options={
                'db_table': 'defeitos',
            },
        ),
        migrations.CreateModel(
            name='GeracaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('quantidade_casos_gerados', models.IntegerField(default=0)),
                ('tokens_utilizados', models.IntegerField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('escopo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geracoes_ia', to='modelos.escopo')),
            ],
            options={
                'db_table': 'geracoes_ia',
            },
        ),
        migrations.AddField(
            model_name='escopo',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escopos', to='modelos.projeto'),
        ),
        migrations.CreateModel(
            name='RodadaDeExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodadas_execucao', to='modelos.projeto')),
            ],
            options={
                'db_table': 'rodadas_execucao',
            },
        ),
        migrations.AddField(
            model_name='execucaodecaso',
            name='rodada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='modelos.rodadadeexecucao'),
        ),
    ]
