# Generated by Django 6.1.1 on 2026-09-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='execucaodecaso',
            constraint=models.UniqueConstraint(fields=('rodada', 'caso_de_teste'), name='caso_unico_por_rodada'),
        ),
    ]
