# Generated by Django 6.1.1 on 2026-10-02 19:26

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_caso_unico_por_rodada'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projeto',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='projeto_nome_unico'),
        ),
    ]
